name: Launch EC2 Instance

on:
  workflow_dispatch:  # manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Launch EC2 Instance
        run: |
          aws ec2 run-instances \
            --image-id ami-0af9569868786b23a \
            --instance-type t2.micro \
            --key-name SNS \
            --security-group-ids sg-0fef0819f181d85b9 \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=MyGitHubEC2}]'
